new_build

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -1,6 +1,42 @@
 version: 0.2
 
+env: 
+  secrets-manager:
+    SONAR_TOKEN: prod/v1/sonar:SonarToken
+    SONAR_HOST: prod/v1/sonar:Host
+    SONAR_PROJECT_KEY: prod/v1/sonar:Project
+    SONAR_ORGANIZATION: prod/v1/sonar:Organization
+
 phases:
+  pre_build:
+    commands:
+      - echo Installing Sonar Scanner...
+      - export SONAR_SCANNER_VERSION=6.2.1.4610
+      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
+      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
+      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
+      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
+      - export SONAR_SCANNER_OPTS="-server"
+      - echo Sonar Scanner installation complete.
+
+  scanning:
+    commands:
+      - echo Running Sonar Scanner...
+      - sonar-scanner \
+        -Dsonar.organization=$SONAR_ORGANIZATION \
+        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
+        -Dsonar.sources=. \
+        -Dsonar.host.url=$SONAR_HOST
+      - echo Sonar Scanner run complete.
+      - sleep 5
+      - curl $SONAR_HOST/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY > result.json
+      - cat result.json
+      - |
+        if [ "$(jq -r '.projectStatus.status' result.json)" == "ERROR" ]; then
+          echo "Quality Gate failed, aborting build.";
+          exit 1;
+        fi
+
   install:
     runtime-versions:
       nodejs: 20
@@ -16,6 +52,7 @@ phases:
   post_build:
     commands:
       - echo Build completed. Output directory
+      # You can add deployment or further processing here, e.g. S3 upload
 
 artifacts:
   files:
